name: lojaonline2
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_staggered_grid_view: ^0.7.0
  
  carousel_slider: ^4.2.1
  transparent_image: ^2.0.1
  scoped_model: ^2.0.0
  
  url_launcher: ^6.2.5
  path_provider: ^2.1.2
  firebase_core: ^2.28.0
  firebase_auth: ^4.19.0
  cloud_firestore: ^4.16.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
